apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-problem
rules:
  - apiGroups: ["", "metrics.k8s.io"]
    resources:
      - nodes
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
